#!/bin/bash
DEST="$HOME/.sync"

cd $DEST
git init
git add .
git commit -m "initial commit"
git branch -M main
git remote add origin git@github.com:voepiter/.sync.git
git push -u origin main
git remote set-url origin git@github.com:voepiter/.sync.git