#!/bin/bash
DEST="$HOME/.sync"

mkdir -p "$DEST/home" 
cd ~

# Домашние конфиги (копируем только нужное, без кэша .git итд )
rsync -av --exclude='.cache' --exclude='.git' --exclude='.zsh_history' --exclude='uv' --exclude='python' \
    ~/.bashrc ~/.alias ~/.dircolors ~/.zshrc ~/.config ~/.alias ~/doc  \
    "$DEST/home"

#mc syntax skins
cp -r --parent .local/share/mc "$DEST/home"   
# rtorrents
cp .rtorrent.rc "$DEST/home"

#/etc
mkdir -p "$DEST/etc"
# wsl конфиги
cp /etc/wsl.conf "$DEST/etc/"
# apt dist repo
mkdir -p "$DEST/etc/apt"
cp /etc/apt/sources.list "$DEST/etc/apt"
# vps
#cp -r /etc/iptables "$DEST/etc"
#cp -r /etc/fail2ban "$DEST/etc"

# cинхронизация c git 
cd "$DEST"
git add .
git commit -m "sync $(hostname) $(date +'%y.%m.%d %H:%M')"
git push origin main --quiet


